server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER_SERVICE
          uri: lb://USER_SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT_SERVICE
          uri: lb://DEPARTMENT_SERVICE
          predicates:
            - Path=/departments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
