# Microservices using SpringBoot | Full Example	
# thanks to: https://www.youtube.com/watch?v=BnknNTN8icw

# Kubernetes Tutorial For Beginners - with Java and Spring Boot Microservices
# https://github.com/in28minutes/kubernetes-crash-course
# https://www.youtube.com/watch?v=rTNR7vDQDD8

server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
